apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: autoshop-webapp
  name: autoshop-webapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
