apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: autoshop
  name: autoshop
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: autoshop
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: autoshop
    spec:
      containers:
        - image: autoshop:latest
          name: backend-container
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /app/data
              name: autoshop-webapp
      restartPolicy: Always
      volumes:
        - name: autoshop-webapp
          persistentVolumeClaim:
            claimName: autoshop-webapp
