version: '3.4'

name: autoshop

services:
  autoshop:
    container_name: backend_container
    image: ${DOCKER_REGISTRY-}autoshop
    build:
      context: .
      dockerfile: AutoShop/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - mongodb
      - sqlserver

  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    ports:
      - "27017:27017"

  sqlserver:
    container_name: sqlserver_container
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Polo1234polo"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"