version: '3.4'

name: autoshop

services:
  autoshop:
    container_name: backend_container
    image: autoshop:latest
    build:
      context: .
      dockerfile: AutoShop/Dockerfile
    ports:
      - "5000:80"
    volumes:
      - autoshop_webapp:/app/data

  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  sqlserver:
    container_name: sqlserver_container
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Polo1234polo"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  autoshop_webapp:
  mongodb_data:
  sqlserver_data:
